### ISSUE TITLE
Allow text / file uploads

### ISSUE THREAD

**Issue by popey456963** [Senither/ShareX-Media-Server#1]
Awesome PHP program, however it is a shame you can only upload images when ShareX supports such a variety of file types.

**Comment by Senither** [comment]
I haven't really touched the application in awhile, when I first made it I had only planned on using it for sharing screenshots, so I never got around to adding any other features to it. I do have some plans to rewrite the entire site using a newer version of Laravel that also supports more of ShareX features, I'm currently occupied with other projects but I'll get on it once I have more free time^^

**Comment by Senither** [comment]
There is now text file support in the media server now, allowing you to upload code and sharing it with people through the media server. Example of the text file preview: https://senither.is-just-a-me.me/t/TheAlertWearyChin

**Comment by popey456963** [comment]
That's really cool!  Glad to see you're still working on this :)
