### ISSUE TITLE
Web Uploads

### ISSUE THREAD

**Issue by LouisHacking** [Senither/ShareX-Media-Server#12]
I'm both a Mac and windows user...

Would it be possible to upload media to ShareX-Media-Server through the website?

I'm yet to find a Mac alternative to ShareX

**Comment by Senither** [comment]
The API isn't built to only work for ShareX, you could technically send requests through CURL or any other system that is able to make an HTTP request, so if you can find a Mac alternative that allows you to send the files to a custom URL it should work.

The ability to upload images, files, and shorten URLs directly on the website itself is something I've been planning on adding for a while, I can start working on it soon so you can use that too.

**Comment by Senither** [comment]
ShareX doesn't detect the first few seconds until I actually open the modal, however, support for uploading images, text files, and shortening URLs directly on the dashboard is now a thing.

![https://senither.is-just-a-me.me/i/afjV5LbH4.gif](https://senither.is-just-a-me.me/i/afjV5LbH4.gif "ShareX upload via dashboard example")

Hopefully that helps you use the media server on your Mac until you find an alternative for ShareX 👍

**Comment by LouisHacking** [comment]
Thank you!

Managed to also use Automator on Mac to screenshot, then use curl to upload it.

The resolution of my MacBook seems to be too high and the file is too large to upload. Had to resort to scaling it to 40% of the original size.

Thanks again ;)

**Comment by Senither** [comment]
I'm glad to hear Nice you got it working on your Mac too 👍 

The file size issue might just be the PHP file upload size limit being too small, if it's left at the default it will limit all file sizes to be 2 MBs or less, you could try editing your PHP config and raise the limit to something like 10 or 20 MB and test if you can upload full-scale images then.

**Comment by LouisHacking** [comment]
Sorted! Super!
