### ISSUE TITLE
Sharex Response Type

### ISSUE THREAD

**Issue by DubStepMad** [Senither/ShareX-Media-Server#2]
Got everything else working but the response type, just outputs some html.

ShareX's new update also changes it so you have the following options only.

`JSON`, `XML` and `Regex`

**Comment by Senither** [comment]
The rewrite of the API now returns all API responses in a `JSON` format, you can still specify if you want the URL as plain text by providing an `Accept` header with `text/plain` value, there is a guide in the readme on how to setup ShareX with the JSON responses too.
