### ISSUE TITLE
Add support for uploading any file type

### ISSUE THREAD

**Issue by teo0781** [Senither/ShareX-Media-Server#20]
Support videos and other files, currently it only allows images.

So for example, i could upload video.mp4 and RandomZipName.zip (just examples)

Or is this already a feature, if it is already a feature, it would be nice for it to get listed.

**Comment by Senither** [comment]
The media server itself supports image uploads, text file uploads, and shorten URLs, all three are documented in the wiki.

Image example: https://what-even-is.senither.com/i/ImpossibleSpectacularBears
Text example: https://avaire.is-just-a-me.me/t/DeeplySilkyFact
URL example: https://alexis.is-just-a-me.me/u/HystericalRedControl

It doesn't currently support video or zip files, and neither of those types really works within the currently supported upload types, however, I could make a fourth generic file uploader to just share uploaded files, regardless of the type, question is if ShareX supports generic file uploads, if nothing else I could add support for uploading files directly in the website and share them that way, similarly to how images, text, and URLs can be uploaded/shortened directly in the dashboard.

**Comment by teo0781** [comment]
Yes, ShareX does indeed support custom files, no matter the file type, ex. the "Upload with ShareX" whenever you right click a file in the windows file explorer. 

There is also support for folders, although, it isn't very needed. (ShareX window -> Upload -> Upload file...)
https://cdn.teo0781.xyz/i/x98PdY
https://cdn.teo0781.xyz/i/uqU8W0

Adding support for these functions would be amazing.

**Comment by Senither** [comment]
Not yet, haven't even started on it, I was at work yesterday when I last commented on the PR and I'm at work again now, as I write code for a living too I'm not always up for writing even more code when I get home, so don't expect anything to really happen regarding the project until the weekend unless I find some time earlier this week, or if someone else wants to work on it instead.

**Comment by teo0781** [comment]
Understandable, sorry if i turned out to be rude.

**Comment by teo0781** [comment]
@Senither This may be a problem. I can not access my server after updating with `git pull`

Error code: `Undefined variable: files (View: /var/www/media-server/resources/views/dashboard/stats.blade.php) (View: /var/www/media-server/resources/views/dashboard/stats.blade.php)`

**Comment by Senither** [comment]
There is a script in the project itself you can use to update with called `update.sh`, running that will run all the necessary commands for you, the issue you're seeing is a caching issue since your old view files is still cached, just clear them with `php artisan cache:clear`(The update script would've done that for you too)

Since the feature has also been implemented now I'll go ahead and close this issue.
