### ISSUE TITLE
[SUGGESTION] Uploaded videos

### ISSUE THREAD

**Issue by teo0781** [Senither/ShareX-Media-Server#24]
Before i suggest anything, just want to say, the generic file uploader is amazing.

So, my suggestion is: If the uploaded file is a .mp4, .mov or something similar (video format), do not make a download page for it, instead just redirect to the direct source, and then it would rely on your browser to render it (firefox, chrome)

EDIT: If possible, also make the url embed in discord, this should be decently easy to do. To bypass the preview limit (8mb), you'd have to put some sort of title in the embed, like gyazo does it.

**Comment by Senither** [comment]
I'm glad you like the implementation of the file uploader.

Regarding your suggestion, I don't think it's a good idea to remove the download button entirely for some file types, however, something that might be nice would be to add a preview button that would allow you to preview the file directly in the media server, that would work with your zip file preview idea too where you can see the contents of a zip file before downloading it.

Creating a preview for some file types, such as images, video formats, music formats, zip files, possibly more in the future, would be pretty nice, it wouldn't get rid of the download button, just add a preview for the file types that support it.

**Comment by teo0781** [comment]
What i was talking about, the download button is purely unecessary for videos, if you redirect it to the actual video, the inbuilt video viewer (firefox or chrome, and more), then it would play the video. And if you right click it, you can simply download it.

**Comment by Senither** [comment]
You could download the files using both the download and preview buttons if the preview button was implemented, the download button just saves you from having to click preview, and then CTRL + S to save the file.

**Comment by teo0781** [comment]
> You could download the files using both the download and preview buttons if the preview button was implemented, the download button just saves you from having to click preview, and then CTRL + S to save the file, don't really see any reason to remove the download button just because the preview button would be added for some file type.s

Actually, now that i think about it, yes. Having the preview take 90% of the screen, and then a button in the corner (like text uploads, with all the current info and the download button)

**Comment by Senither** [comment]
That wasn't really what I was thinking of, my idea is to have three pages:

* Information Page
* Download File
* Preview File

The information and download pages already exist in the form of the `/f/{file}` and `/f/{file}/raw` routes, my idea is to add a `/f/{file}/preview` route that would show a video/music player for video and music files and some way of navigating through zip files, for video and music players you could just CTRL + S to save the file, there wouldn't be any extra information added on top of that page, all the information is already on the info page if people need to go through it.

**Comment by teo0781** [comment]
> That wasn't really what I was thinking of, my idea is to have three pages:
> 
>     * Information Page
> 
>     * Download File
> 
>     * Preview File
> 
> 
> The information and download pages already exist in the form of the `/f/{file}` and `/f/{file}/raw` routes, my idea is to add a `/f/{file}/preview` route that would show a video/music player for video and music files and some way of navigating through zip files, for video and music players you could just CTRL + S to save the file, there wouldn't be any extra information added on top of that page, all the information is already on the info page if people need to go through it.

That's also another good way, really, the only important feature (atleast to me), would be for it to embed in discord without a problem, while still maintaining the current functionality.

**Comment by Senither** [comment]
That shouldn't really be an issue with the system, Discord really likes files having extensions in the URL when rendering embedded previews, so can just append the file extension to the preview URL and you can copy that straight into Discord.

**Comment by Senither** [comment]
Support file types now have a preview button that can be used to preview files before downloading them, the system is set up such that it should be super easy to add more supported file types later down the line, you can see an example of the preview using the link below.

https://what-even-is.avairebot.com/f/wat
