### ISSUE TITLE
Mobile viewing issue

### ISSUE THREAD

**Issue by teo0781** [Senither/ShareX-Media-Server#26]
It does not scale properly, unlike the main control panel, this is when you go to download a file/preview it.![Screenshot_20210629-160557_Firefox.jpg](https://user-images.githubusercontent.com/61596661/123812203-2f2c8a00-d8f4-11eb-9ba3-3833a0aa5b60.jpg)

**Comment by Senither** [comment]
What is your screen resolution on your phone?

Also, is the website only scaling badly on the preview page or on the rest of the site too?

it should be looking like this on smaller devices.
![Screenshot_20210629-161455](https://user-images.githubusercontent.com/8415349/123813548-4ae46000-d8f5-11eb-9b69-2449d0f399ad.jpg)

**Comment by teo0781** [comment]
It only scales badly on the newst added feature, aka. Generic file uploader, other sites are fine.
My screen resolution is 720x1480, i am using the newest version of firefox.

**Comment by Senither** [comment]
I've changed the file preview page in 8b2b2c5fb611aebe6d68b06df9b69687445b1aad to support extra small devices too, should hopefully look fine for you now, you can see an example of what it looks like below.

![https://avaire.is-just-a-me.me/i/AnObtainableLackadaisicalSmile](https://avaire.is-just-a-me.me/i/AnObtainableLackadaisicalSmile)

**Comment by teo0781** [comment]
The latest update fixed it, it now correctly displays.
