### ISSUE TITLE
Preview changes

### ISSUE THREAD

**Issue by ken-colvin** [Senither/ShareX-Media-Server#3]
How do I preview the changes of my Sharex new image?  The issue is, I sometimes copy/paste image and then realize the changes are not correct.  Would be great to have a "Preview Changes" button to see the image as if it was saved or copy/pasted.

**Comment by Senither** [comment]
Seems more related to ShareX itself, and not actually the media server project, you should ask that in [https://github.com/ShareX/ShareX](ShareX/ShareX) instead.
