### ISSUE TITLE
[BUG] Used disk space not updating

### ISSUE THREAD

**Issue by teo0781** [Senither/ShareX-Media-Server#35]
The title explains itself. After you upload the first file, it properly changes the value. After that, no other file seems to affect it. 
There seems to be no error.

(this may be an issue on my end though)

**Comment by Senither** [comment]
Whenever anything is uploaded or deleted from the media server the [CalculateUsedDiskSpace](https://github.com/Senither/ShareX-Media-Server/blob/master/app/Jobs/CalculateUsedDiskSpace.php) job will be dispatched, if you have configured jobs to use a queue, but are not actually running the queued jobs that might be the issue, if the jobs are failing you should also be able to see the error showing up in your `storage/logs/laravel.log` file.

If you don't have a queue worker setup for the site I'd recommend you use `sync` as your queue driver so all the jobs are being executed right after file uploads or deletions, this does make the site slightly slower tho, as the media server is then doing all the disk calculations inside of the users request cycle.

**Comment by teo0781** [comment]
Hello, apologies for the late response, I am not exactly sure how to fix this issue. I've set up the queue worker properly (I think at least). This is the error i get on any new upload.

```
[2022-01-30 14:51:59] local.ERROR: filesize(): stat failed for /var/www/media-server/storage/app/images/1/REDACTEDFORPRIVACY.jpg {"exception":"[object] (ErrorException(code: 0): filesize(): stat failed for /var/www/media-server/storage/app/images/1/REDACTEDFORPRIVACY.jpg at /var/www/media-server/app/Jobs/CalculateUsedDiskSpace.php:74)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/media-server/app/Jobs/CalculateUsedDiskSpace.php(74): filesize()
#2 /var/www/media-server/app/Jobs/CalculateUsedDiskSpace.php(53): App\\Jobs\\CalculateUsedDiskSpace->calculateImageDiskSize()
#3 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\CalculateUsedDiskSpace->handle()
#4 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#6 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#7 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#8 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#9 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#10 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#12 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow()
#13 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#14 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#16 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#17 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#18 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#19 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process()
#20 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob()
#21 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#22 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#23 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#24 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#26 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#27 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#28 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#29 /var/www/media-server/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#30 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#31 /var/www/media-server/vendor/symfony/console/Application.php(1005): Illuminate\\Console\\Command->run()
#32 /var/www/media-server/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#33 /var/www/media-server/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#34 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#35 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#36 /var/www/media-server/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#37 {main}
"}
```

Any idea on how to fix?

**Comment by teo0781** [comment]
Sorry for necro bumping, is there any update to this?
Thanks.

**Comment by imskyyc** [comment]
> Hello, apologies for the late response, I am not exactly sure how to fix this issue. I've set up the queue worker properly (I think at least). This is the error i get on any new upload.
> 
> ```
> [2022-01-30 14:51:59] local.ERROR: filesize(): stat failed for /var/www/media-server/storage/app/images/1/REDACTEDFORPRIVACY.jpg {"exception":"[object] (ErrorException(code: 0): filesize(): stat failed for /var/www/media-server/storage/app/images/1/REDACTEDFORPRIVACY.jpg at /var/www/media-server/app/Jobs/CalculateUsedDiskSpace.php:74)
> [stacktrace]
> #0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
> #1 /var/www/media-server/app/Jobs/CalculateUsedDiskSpace.php(74): filesize()
> #2 /var/www/media-server/app/Jobs/CalculateUsedDiskSpace.php(53): App\\Jobs\\CalculateUsedDiskSpace->calculateImageDiskSize()
> #3 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\CalculateUsedDiskSpace->handle()
> #4 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #5 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
> #6 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
> #7 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
> #8 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
> #9 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
> #10 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #11 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
> #12 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow()
> #13 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
> #14 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #15 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
> #16 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
> #17 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
> #18 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
> #19 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process()
> #20 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob()
> #21 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
> #22 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
> #23 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
> #24 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #25 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
> #26 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
> #27 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
> #28 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
> #29 /var/www/media-server/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
> #30 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
> #31 /var/www/media-server/vendor/symfony/console/Application.php(1005): Illuminate\\Console\\Command->run()
> #32 /var/www/media-server/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
> #33 /var/www/media-server/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
> #34 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
> #35 /var/www/media-server/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
> #36 /var/www/media-server/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
> #37 {main}
> "}
> ```
> 
> Any idea on how to fix?

I just got it working on my server and I’m not seeing any issues with the used disk space counter.

**Comment by teo0781** [comment]
Turns out I just didn't set it up correctly, I apologize for the false issue.
