### ISSUE TITLE
/cp/images returns error.

### ISSUE THREAD

**Issue by DoubleThePsycho** [Senither/ShareX-Media-Server#4]
The software works, even with newer Laravel and PHP versions.
Images upload as they should, are processed and added to the index site.
However, when trying to manage items I get this error:
![image](https://user-images.githubusercontent.com/27337177/85204512-50d45800-b315-11ea-9f8c-91363ee0d531.png)

I know the software hasn't been touched in a few years but I'm posting this in hope that an update is on your schedule somewhere (as mentioned on another issue)

**Comment by Senither** [comment]
It took a while, but this has been fixed in the complete rewrite of the media server, everything in the previous version of the app should now work + a few new features.
