### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by LouisHacking** [Senither/ShareX-Media-Server#6]
Would it be possible to build a URL shortener into this project?

Something similar to [https://polrproject.org/](https://polrproject.org/)

**Comment by Senither** [comment]
Yup, with the recent rewrite of the project the plan is to eventually support all of the ShareX features, like file and text uploads, as-well-as URL shortening.

**Comment by Senither** [comment]
With the merge of #10 there is now support for shortening URLs.

Setup guides for everything in the media server are coming soon too.
